# Generated by Django 2.2 on 2021-04-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bogievkp1',
            name='bogie_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bogievkp1',
            name='bogie_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingsvkp4',
            name='journey_date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bookingsvkp4',
            name='p_destination',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bookingsvkp4',
            name='p_gender',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingsvkp4',
            name='p_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bookingsvkp4',
            name='p_source',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='routevkp1',
            name='route_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seatvkp1',
            name='seat_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seatvkp1',
            name='seat_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stationvkp1',
            name='station_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stationvkp1',
            name='stations_name',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trainvkp1',
            name='arrival_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainvkp1',
            name='departure_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainvkp1',
            name='dest_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trainvkp1',
            name='source_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trainvkp1',
            name='train_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trainvkp1',
            name='train_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='trainvkp1',
            name='train_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
